# ES Module 3

Welcome to Module 3!

Last time, we went over:
    1. Strings and Intergers
    2. Arrays
    3. Tables
    
Today we will continue working with tables, and introduce a new procedure called filtering. Before you start, run the following cell.

In [2]:
# Loading our libraries, i.e. tool box for our module
import numpy as np
from datascience import *

### Paired Programming 
Today we want to introduce a new system of work called paired programming. Wikipedia defines paired programming in the following way:

Pair programming is an agile software development technique in which two programmers work together at one workstation. One, the driver, writes code while the other, the observer or navigator, reviews each line of code as it is typed in. The two programmers switch roles frequently.

This methodolgy is quite known in the computer science realm, and we want to try and see how well it would work in our little class room. Hopefully we would all benefit from this, by closing the gap between more experienced coders and less so we could move forward to more advanced topics! Additionally, there is always the benefit of having a friend when all hell breaks loose (or the code just would not work..)

So after this brief introduction, please team up with a class-mate, hopefully someone you did not know from before that is at a slightly different level of programming experience.

Please start now, as one takes the controls and the other is reviewing the code.

## 0. Comments

Comments are ways of making your code more human readable. It's good practice to add comments to your code so someone else reading your code can get an idea of what's going on. 

You can add a comment to your code by preceeding it with a `#` symbol. When the computer sees any line preceeded by a `#` symbol, it'll ignore it. Here's an example below: 

In [3]:
# Calculating the total number of pets in my house.
num_cats = 4
num_dogs = 10
total = num_cats + num_dogs
total

14

Now, write a comment in the cell below explaining what it is doing, then run the cell to see if you're correct.

In [4]:
animals = make_array('Cat', 'Dog', 'Bird', 'Spider')
num_legs = make_array(4, 4, 2, 8)
my_table = Table().with_columns('Animal', animals,
                               'Number of Legs', num_legs)
my_table

Animal | Number of Legs
Cat    | 4
Dog    | 4
Bird   | 2
Spider | 8

## 1. Tables (Continued) 

It is time to practice tables again. We want to load the table files you have uploaded last module. This time, you do it by yourself. Load the table "inmates_by_year.csv" and "correctional_population.csv" and assign it to a variable. Remember, to load a table we use `Table.read_table()` and pass the name of the table as an argument to the function.

In [5]:
inmates_by_year = Table.read_table('inmates_by_year.csv')
correctional_population = Table.read_table('correctional_population.csv')


Good job! Now we have all the tables loaded. 

It is time to extract some information from these tables!
In the next several cells, we would guide you through a quick manipulation that will allow us to extract information about the entire correctional population using both tables we have loaded above.

In the correctional_population table, we are given data about the number of supervised per 100,000 U.S. adult residents. That means that if we want to have the approximated number of the entire population under supervision we need to multiply by 100,000.

In [6]:
# First, extract the column name "Number supervised per 100,000 U.S. adult residents/c" from 
# the correctional_population table and assign it to the variable provided.
c_p = correctional_population.column('Number supervised per 100,000 U.S. adult residents/c')
c_p

array(['3,060', '3,160', '3,190', '3,210', '3,160', '3,100', '3,000',
       '2,930', '2,880', '2,830', '2,780', '2,710'], 
      dtype='<U5')

#### filtering
When you run the cell above, you may notice that the values in our array are actually strings (you can tell because each value has quotation marks around it). However, we can't do mathematical operations on strings, so we'll have to convert this array first so it has integers instead of strings. This is called filtering, or cleaning the data, so we can actually do some work on it. In the following cells, when you see the `# filtering` sign, know that we have yet to cover this topic.

Run the following cell to do clean the table. We'll go over how to do this in a later section of this module. If you have any questions about how it works, feel free to ask any of us!

In [33]:
# filtering
def string_to_int(val):
    return int(val.replace(',', ''))

c_p = correctional_population.apply(string_to_int, 'Number supervised per 100,000 U.S. adult residents/c')

Now, let's continue finding the real value of c_p. 

In [13]:
# In this cell, multiply the correctional population column name "Number supervised per 100,000 U.S. adult residents/c" 
# by 100000 and assign it to a new variable (c_p stands for correctional population)
real_c_p = c_p * 100000
real_c_p

array([306000000, 316000000, 319000000, 321000000, 316000000, 310000000,
       300000000, 293000000, 288000000, 283000000, 278000000, 271000000])

Next we want to assign the Total column from inmates_by_year to a variable in order to be able to operate on it.

In [14]:
total_inmates = inmates_by_year.column('Total')
total_inmates

array(['747,500', '765,800', '780,200', '785,500', '767,400', '748,700',
       '735,600', '744,500', '731,200', '744,600', '728,200'], 
      dtype='<U7')

Again, run the following line to convert the values in `total_inmates` to ints.

In [15]:
# filtering 
total_inmates = inmates_by_year.apply(string_to_int, 'Total')
total_inmates

array([747500, 765800, 780200, 785500, 767400, 748700, 735600, 744500,
       731200, 744600, 728200])

#### Switch position, the navigator now takes the wheel.

Now that we have the variables holding all the information we want to manipulate, we can start digging into it.

We want to come up with a scheme that will allow us to see the precentage of people that are incarcerated, from the total supervised population, by year.

Before we do that, though, examine your two variables, `total_inmates` and `real_c_p` and their corresponding tables. Do you foresee any issues with directly comparing these two tables? 

The `correctional_population` table has a row corresponding to 2000, which `inmates_by_year` does not have. This not only means that the data from our two tables doesn't match up, but also that our arrays are two different lengths. Recall that we cannot do operations on arrays with different lengths. 

To fix this, run the following cell, in which we get rid of the value corresponding to the year 2000 from `real_c_p`. Again, if you have questions about how this works, feel free to ask us! 

In [16]:
# filtering
real_c_p = real_c_p.take(np.arange(1, real_c_p.size))
real_c_p

array([316000000, 319000000, 321000000, 316000000, 310000000, 300000000,
       293000000, 288000000, 283000000, 278000000, 271000000])

Now our arrays both correspond to data from the same years and we can do operations with both of them!

In [30]:
# Write a short code that stores the precentage of people incarcerated from the supervised population 
# (rel stands for relative, c_p stands from correctional population)
inmates_rel_c_p = (total_inmates / real_c_p) * 100
inmates_rel_c_p

array([ 0.23655063,  0.2400627 ,  0.24305296,  0.24857595,  0.24754839,
        0.24956667,  0.25105802,  0.25850694,  0.25837456,  0.26784173,
        0.26870849])

Now, this actually gives us useful information!
Why not write it down? Please write down what this information tells you about the judicial infrastructure - we are looking for more mathy/dry explanation (rather than observation of how poorly it is). 

In [31]:
# A simple sentence will suffice, we want to see intuitive understanding. Please call a teacher when done to check!
extract_information_shows = "The percentage of people, supervisied by US adult correctional system, who are incarcerated"

For a final touch, please sort inmates_rel_c_p by descending order in the next cell. We won't tell you how to sort, this time please check the last lab module on how to sort a table. It is an important quality of a programmer to be able to reuse code you already have.  

Hint: Remember that you can only use `sort` on tables. How might you manipulate your array so that you can sort it?

In [32]:
# Please sort inmates_rel_c_p in descending order and print it out
inmates_rel_c_p = Table().with_columns('Inmate_percentage', inmates_rel_c_p)
inmates_rel_c_p.sort('Inmate_percentage',descending = True)
inmates_rel_c_p

Inmate_percentage
0.236551
0.240063
0.243053
0.248576
0.247548
0.249567
0.251058
0.258507
0.258375
0.267842
... (1 rows omitted)

#### Before starting, please switch positions

## Filtering

Right now, we can't really get much extra information from our tables other than by sorting them. In this section, we'll learn how to filter our data so we can get more useful insights from it. This is especially useful when dealing with larger data sets!

For example, say we wanted insights about the total number of inmates after 2012. We can find this out using the `where` function. Check out the cell below for an example of how to use this. 

In [48]:
inmates_by_year.where('Year', are.above(2012))

Year | Total   | Standard error/a
2013 | 731,200 | 8,040
2014 | 744,600 | 8,380
2015 | 728,200 | 7,380

Notice that `where` takes in two arguments: the name of the column, and the condition we are filtering by. 

Now, try it for yourself! In the cell below, filter `correctional_population` so it only includes years after 2008. 

Year | Number supervised per 100,000 U.S. adult residents/c | U.S. adult residents under correctional supervision
2009 | 3,100                                                | 1 in 32
2010 | 3,000                                                | 1 in 33
2011 | 2,930                                                | 1 in 34
2012 | 2,880                                                | 1 in 35
2013 | 2,830                                                | 1 in 35
2014 | 2,780                                                | 1 in 36
2015 | 2,710                                                | 1 in 37

If you run the following cell, you'll find a complete description of all such conditions (which we'll call predicates) that you can pass into where. This information can also be found [here](https://www.inferentialthinking.com/chapters/05/2/selecting-rows.html).

In [51]:
functions = make_array('are.equal_to(Z)', 'are.above(x)', 'are.above_or_equal_to(x)', 'are.below(x)', 
                       'are.below_or_equal_to(x)', 'are.between(x, y)', 'are.strictly_between(x, y)',
                      'are.between_or_equal_to(x, y)', 'are.containing(S)')
descriptions = make_array('Equal to Z', 'Greater than x', 'Greater than or equal to x', 'Below x', 
                         'Less than or equal to x', 'Greater than or equal to x, and less than y',
                         'Greater than x and less than y', 'Greater than or equal to x, and less than or equal to y',
                         'Contains the string S')
predicates = Table().with_columns('Predicate', functions,
                                 'Description', descriptions)
predicates

Predicate                     | Description
are.equal_to(Z)               | Equal to Z
are.above(x)                  | Greater than x
are.above_or_equal_to(x)      | Greater than or equal to x
are.below(x)                  | Below x
are.below_or_equal_to(x)      | Less than or equal to x
are.between(x, y)             | Greater than or equal to x, and less than y
are.strictly_between(x, y)    | Greater than x and less than y
are.between_or_equal_to(x, y) | Greater than or equal to x, and less than or equal to y
are.containing(S)             | Contains the string S

Now, we'll be using filtering to gain more insights about our two tables. Before we start, be sure to run the following cell so we can ensure every column we're working with is numerical.

In [80]:
inmates_by_year = inmates_by_year.drop('Total').with_column('Total', total_inmates).select('Year', 'Total', 'Standard error/a')
correctional_population = correctional_population.drop('Number supervised per 100,000 U.S. adult residents/c').with_column('Number supervised per 100,000 U.S. adult residents/c', c_p).select('Year', 'Number supervised per 100,000 U.S. adult residents/c', 'U.S. adult residents under correctional supervision ').relabel('U.S. adult residents under correctional supervision ', 'U.S. adult residents under correctional supervision')


First, find the mean of the total number of inmates. Hint: You can use the `np.mean()` function on arrays to calculate this.

In [64]:
avg_inmates = np.mean(inmates_by_year.column('Total'))
avg_inmates

752654.54545454541

Now, filter `inmates_by_year` to find data for the years in which the number of total inmates was under the average.

In [70]:
filtered_inmates = inmates_by_year.where('Total', are.below(avg_inmates))
filtered_inmates

Year | Total  | Standard error/a
2005 | 747500 |  ~
2010 | 748700 | 5,430
2011 | 735600 | 6,010
2012 | 744500 | 7,680
2013 | 731200 | 8,040
2014 | 744600 | 8,380
2015 | 728200 | 7,380

What does this tell you about the total inmate population? Write your answer in the cell below.

In [77]:
answer = "YOUR TEXT HERE"

#### Before continuing, please switch positions.

Now, similarly, find the average number of adults under correctional supervision, and filter the table to find the years in which the number of adults under correctional supervision was under the average.

In [75]:
avg = np.mean(correctional_population.column('Number supervised per 100,000 U.S. adult residents/c'))
filtered_c_p = correctional_population.where('Number supervised per 100,000 U.S. adult residents/c', are.below(avg))
filtered_c_p

Year | Number supervised per 100,000 U.S. adult residents/c | U.S. adult residents under correctional supervision
2010 | 3000                                                 | 1 in 33
2011 | 2930                                                 | 1 in 34
2012 | 2880                                                 | 1 in 35
2013 | 2830                                                 | 1 in 35
2014 | 2780                                                 | 1 in 36
2015 | 2710                                                 | 1 in 37

Do the years match up? Does this make sense based on the proportions you calculated above in `inmates_rel_c_p`?

In [78]:
answer = "YOUR TEXT HERE"

Now, from `correctional_population`, filter the table so the value of U.S. adult residents under correctional supervision is 1 in 31. Remember, the values in this column are strings.

In [84]:
c_p_1_in_34 = correctional_population.where('U.S. adult residents under correctional supervision', are.containing('1 in 31'))
c_p_1_in_34

Year | Number supervised per 100,000 U.S. adult residents/c | U.S. adult residents under correctional supervision
2006 | 3190                                                 | 1 in 31
2007 | 3210                                                 | 1 in 31

Now, we have one last challenge exercise. Before doing this, finish the challenge exercises from last module. We highly encourage you to work with your partner on this one.

In the following cell, find the year with the max number of supervised adults for which the proportion of US adult residents under correctional supervision was 1 in 32. 

In [85]:
one_in_32 = correctional_population.where('U.S. adult residents under correctional supervision', are.containing('1 in 32'))
one_in_32_sorted = one_in_32.sort('Number supervised per 100,000 U.S. adult residents/c', descending = True)
year = one_in_32_sorted.column('Year').item(0)
year

2008

Congratulations, you're done with this module! Before you leave, please fill out this [link](https://docs.google.com/a/berkeley.edu/forms/d/1KQHzw-rh_E--lnQ7ItLrOcH7WJUTexDiKMLcuPwClzo/edit?usp=drive_web) to give us feedback on how we can make these modules more useful for you.